
export enum AvatarBoneEnum {
    pelvis = "a",
    pelvis_l = "b",
    hip_l = "c",
    knee_l = "d",
    foot_l = "e",
    pelvis_r = "f",
    hip_r = "g",
    knee_r = "h",
    foot_r = "i",
    trunk = "j",
    chest_l = "k",
    shoulder_l = "l",
    elbow_l = "m",
    hand_l = "n",
    chest_r = "o",
    shoulder_r = "p",
    elbow_r = "q",
    hand_r = "r",
    head = "s",
    head2 = "t",
    target_head = "9",
    target_chest = "2",
    target_shoulder_l = "3",
    target_shoulder_r = "4",
    target_elbow_l = "0",
    target_elbow_r = "1",
    target_hand_l = "7",
    target_hand_r = "8",
    target_knee_l = "_",
    target_knee_r = "-",
    target_foot_l = "5",
    target_foot_r = "6",
};

export const EXPORTED_BONES = [
    AvatarBoneEnum.pelvis,
    AvatarBoneEnum.pelvis_l,
    AvatarBoneEnum.hip_l,
    AvatarBoneEnum.knee_l,
    AvatarBoneEnum.foot_l,
    AvatarBoneEnum.pelvis_r,
    AvatarBoneEnum.hip_r,
    AvatarBoneEnum.knee_r,
    AvatarBoneEnum.foot_r,
    AvatarBoneEnum.trunk,
    AvatarBoneEnum.chest_l,
    AvatarBoneEnum.shoulder_l,
    AvatarBoneEnum.elbow_l,
    AvatarBoneEnum.hand_l,
    AvatarBoneEnum.chest_r,
    AvatarBoneEnum.shoulder_r,
    AvatarBoneEnum.elbow_r,
    AvatarBoneEnum.hand_r,
    AvatarBoneEnum.head,
    AvatarBoneEnum.head2,
];

export enum BodyPoseKey {
    nose = "nose",
    left_eye_inner = "left_eye_inner",
    left_eye = "left_eye",
    left_eye_outer = "left_eye_outer",
    right_eye_inner = "right_eye_inner",
    right_eye = "right_eye",
    right_eye_outer = "right_eye_outer",
    left_ear = "left_ear",
    right_ear = "right_ear",
    left_mouth = "left_mouth",
    right_mouth = "right_mouth",
    left_shoulder = "left_shoulder",
    right_shoulder = "right_shoulder",
    left_elbow = "left_elbow",
    right_elbow = "right_elbow",
    left_wrist = "left_wrist",
    right_wrist = "right_wrist",
    left_pinky = "left_pinky",
    right_pinky = "right_pinky",
    left_index = "left_index",
    right_index = "right_index",
    left_thumb = "left_thumb",
    right_thumb = "right_thumb",
    left_hip = "left_hip",
    right_hip = "right_hip",
    left_knee = "left_knee",
    right_knee = "right_knee",
    left_ankle = "left_ankle",
    right_ankle = "right_ankle",
    left_heel = "left_heel",
    right_heel = "right_heel",
    left_foot_index = "left_foot_index",
    right_foot_index = "right_foot_index",
    // gost created by me
    target_chest = "target_chest",
    target_head = "target_head",
}

const MediaPipeRelation = [
    BodyPoseKey.nose,
    BodyPoseKey.left_eye_inner,
    BodyPoseKey.left_eye,
    BodyPoseKey.left_eye_outer,
    BodyPoseKey.right_eye_inner,
    BodyPoseKey.right_eye,
    BodyPoseKey.right_eye_outer,
    BodyPoseKey.left_ear,
    BodyPoseKey.right_ear,
    BodyPoseKey.left_mouth,
    BodyPoseKey.right_mouth,
    BodyPoseKey.left_shoulder,
    BodyPoseKey.right_shoulder,
    BodyPoseKey.left_elbow,
    BodyPoseKey.right_elbow,
    BodyPoseKey.left_wrist,
    BodyPoseKey.right_wrist,
    //dedo menique
    BodyPoseKey.left_pinky,
    BodyPoseKey.right_pinky,
    //dedo indice
    BodyPoseKey.left_index,
    BodyPoseKey.right_index,
    //dedo pulgar
    BodyPoseKey.left_thumb,
    BodyPoseKey.right_thumb,
    BodyPoseKey.left_hip,
    BodyPoseKey.right_hip,
    BodyPoseKey.left_knee,
    BodyPoseKey.right_knee,
    BodyPoseKey.left_ankle,
    BodyPoseKey.right_ankle,
    BodyPoseKey.left_heel,
    BodyPoseKey.right_heel,
    BodyPoseKey.left_foot_index,
    BodyPoseKey.right_foot_index,
];

export const DEFAULT_BOTTOM_VALUES = [
    {
        "name": "left_knee",
        "x": 0.07426603138446808,
        "y": 0.42307138442993164,
        "z": 0.019249558448791504
    },
    {
        "name": "right_knee",
        "x": -0.09451748430728912,
        "y": 0.3935917913913727,
        "z": 0.03170658275485039
    },
    {
        "name": "left_heel",
        "x": 0.0934494286775589,
        "y": 0.8205045461654663,
        "z": 0.14703066647052765
    },
    {
        "name": "right_heel",
        "x": -0.08001966774463654,
        "y": 0.8012871146202087,
        "z": 0.18003836274147034
    },
];

export { MediaPipeRelation };