
export enum AvatarBoneEnum {
    pelvis = "pelvis",
    hip_l = "hipL",
    leg_l = "legL",
    foot_l = "footL",
    foot2_l = "foot2L",
    hip_r = "hipR",
    leg_r = "legR",
    foot_r = "footR",
    foot2_r = "foot2R",
    trunk = "trunk",
    elbow_l = "elbowL",
    arm_l = "armL",
    hand_l = "handL",
    hand2_l = "hand2L",
    elbow_r = "elbowR",
    arm_r = "armR",
    hand_r = "handR",
    hand2_r = "hand2R",
    head = "head",
    head2 = "head2",
    target_arm_l = "target_armL",
    target_arm_r = "target_armR",
    target_chest = "target_chest",
    target_elbow_l = "target_elbowL",
    target_elbow_r = "target_elbowR",
    target_foot_l = "target_footL",
    target_foot_r = "target_footR",
    target_hand_l = "target_handL",
    target_hand_r = "target_handR",
    target_head = "target_head",
    target_knee_l = "target_kneeL",
    target_knee_r = "target_kneeR",
}

export enum BodyPoseKey {
    right_shoulder = "right_shoulder",
    left_shoulder = "left_shoulder",
    right_ear = "right_ear",
    left_ear = "left_ear",
    target_chest = "target_chest",
    target_head = "target_head",
    left_knee = "left_knee",
    left_heel = "left_heel",
    right_knee = "right_knee",
    right_heel = "right_heel",
    right_elbow = "right_elbow",
    right_wrist = "right_wrist",
    left_elbow = "left_elbow",
    left_wrist = "left_wrist",
}