
export enum AvatarBoneEnum {
    pelvis = "a",
    pelvis_l = "b",
    hip_l = "c",
    foot_l = "d",
    foot2_l = "e",
    pelvis_r = "f",
    hip_r = "g",
    foot_r = "h",
    foot2_r = "i",
    trunk = "j",
    elbow_l = "k",
    arm_l = "l",
    hand_l = "m",
    hand2_l = "n",
    elbow_r = "o",
    arm_r = "p",
    hand_r = "q",
    hand2_r = "r",
    head = "s",
    head2 = "t",
    target_head = "9",
    target_chest = "2",
    target_shoulder_l = "3",
    target_shoulder_r = "4",
    target_elbow_l = "0",
    target_elbow_r = "1",
    target_hand_l = "7",
    target_hand_r = "8",
    target_knee_l = "_",
    target_knee_r = "-",
    target_foot_l = "5",
    target_foot_r = "6",
}

export enum BodyPoseKey {
    right_shoulder = "right_shoulder",
    left_shoulder = "left_shoulder",
    right_ear = "right_ear",
    left_ear = "left_ear",
    target_chest = "target_chest",
    target_head = "target_head",
    left_knee = "left_knee",
    left_heel = "left_heel",
    right_knee = "right_knee",
    right_heel = "right_heel",
    right_elbow = "right_elbow",
    right_wrist = "right_wrist",
    left_elbow = "left_elbow",
    left_wrist = "left_wrist",
    left_hip = "left_hip",
    right_hip = "right_hip",
    nose = "nose",

}